# Generated by Django 5.2.6 on 2025-09-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprediction',
            name='assignments',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='studentprediction',
            name='participation',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='studentprediction',
            name='previous_gpa',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='studentprediction',
            name='study_hours',
            field=models.FloatField(default=0),
        ),
    ]
